const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');

/**
 * Generates the stripdown package in node_modules.
 */
async function generateWrapper(usageMap, projectRoot) {
  const stripdownDir = path.join(projectRoot, 'node_modules', 'stripdown');
  await fs.ensureDir(stripdownDir);

  const exports = [];
  const packageJson = {
    name: 'stripdown',
    version: '1.0.0',
    description: 'Auto-generated stripped dependency wrapper',
    main: 'index.js'
  };

  const collisionMap = new Map(); // name -> count
  const indexLines = [
    '// Auto-generated by stripdown',
    '// Time: ' + new Date().toISOString(),
    ''
  ];

  for (const [pkgName, usedSet] of usageMap.entries()) {
    indexLines.push(`// --- ${pkgName} ---`);
    
    if (usedSet.has('*')) {
      // Whole package export
      const safeName = pkgName.replace(/[^a-zA-Z0-9]/g, '_');
      indexLines.push(`const ${safeName} = require('${pkgName}');`);
      exports.push(`${safeName}`);
    } else {
      // Specific exports
      const functions = Array.from(usedSet);
      if (functions.length === 0) continue;

      const destructured = [];
      functions.forEach(fn => {
        if (collisionMap.has(fn)) {
          // Collision! Prefix with package name
          const prefixedName = `${pkgName.replace(/[^a-zA-Z0-9]/g, '_')}_${fn}`;
          indexLines.push(`const { ${fn}: ${prefixedName} } = require('${pkgName}');`);
          exports.push(prefixedName);
          console.warn(chalk.yellow(`[Wrapper] Collision detected for "${fn}" in package "${pkgName}". Exported as "${prefixedName}".`));
        } else {
          destructured.push(fn);
          exports.push(fn);
          collisionMap.set(fn, 1);
        }
      });

      if (destructured.length > 0) {
        indexLines.push(`const { ${destructured.join(', ')} } = require('${pkgName}');`);
      }
    }
    indexLines.push('');
  }

  indexLines.push('module.exports = {');
  indexLines.push('  ' + exports.join(',\n  '));
  indexLines.push('};');

  await fs.writeFile(path.join(stripdownDir, 'index.js'), indexLines.join('\n'));
  await fs.writeJson(path.join(stripdownDir, 'package.json'), packageJson, { spaces: 2 });

  // Create a manifest for debugging
  const manifest = {
    generatedAt: new Date().toISOString(),
    packages: {}
  };
  for (const [pkg, used] of usageMap.entries()) {
    manifest.packages[pkg] = Array.from(used);
  }
  await fs.writeJson(path.join(stripdownDir, '.stripdown-manifest.json'), manifest, { spaces: 2 });

  return stripdownDir;
}

module.exports = {
  generateWrapper
};
